### ISSUE TITLE
tablebooking cashed up under incorrect outlet

### ISSUE THREAD

**Issue by jakers07** [kayordDX/pos#2] opened 2024-10-15 10:08 UTC
tablebooking cashed up under incorrect outlet.  Example:

"TableBookingId"	"Waiter"	"TableId"	"BookingOutlet"	"BookingDate"	"CloseDate"	"CashUpOutlet"
13981	"Megan v.d Westhuizen"	66	"Ruimsig Country Club"	"2024-10-14 12:23:39.732908+00"	"2024-10-14 14:38:28.105304+00"	"Clearwater Mall"

SELECT 
tb."Id" as "TableBookingId"
,u."Name" as "Waiter",
tb."TableId",
o."Name" as "BookingOutlet",
tb."BookingDate",
tb."CloseDate",
co."Name" as "CashUpOutlet"
FROM public."TableBooking" tb
join public."Table" t on t."TableId" = tb."TableId"
join public."Section" s on s."Id" = t."SectionId"
join public."Outlet" o on o."Id" = s."OutletId"
join public."User" u on u."UserId"=tb."UserId"
join public."CashUpUser" cu on cu."Id" = tb."CashUpUserId"
join public."Outlet" co on co."Id" = cu."OutletId"
where 
tb."Id" = 13981
and
co."Id" <> o."Id"

![image](https://github.com/user-attachments/assets/40ad1e4c-4942-4b7f-85a2-f98529cf4573)

**Comment by jakers07** [comment] 2024-10-15 10:22
The waiter started the day at Clearwater and moved to Ruimsig.  Her Ruimsig tables were also cashed up when they cashed he up at Clearwater

**Comment by Stonck08** [comment] 2024-10-15 19:16
Hi @jakers07,

Thank you for logging this issue regarding the TableBooking being cashed up under the incorrect outlet.

I’ve reviewed the example provided, and it appears the issue arises from the discrepancy between the BookingOutlet and the CashUpOutlet. Specifically, in the case of TableBookingId 13981, the booking was made at "Ruimsig Country Club" but cashed up at "Clearwater Mall."

The root cause seems to be related to how the outlets are linked during the cash-up process. As you suggested, the missing salesperiodid is likely the key factor. We’ll implement the fix by ensuring the salesperiodid is included in the cash-up logic, which will properly align the CashUpOutlet with the original BookingOutlet.

I’ll proceed with testing this solution to ensure it resolves the issue, and I’ll keep you updated once the fix has been applied.

After rigorous testing the bug fix will be deployed to production on our earliest deployment slot available in 2025, Merry Christmas and a happy new year to you.

Thank you for bringing this to our attention.

Best regards,
Stefan

**Closed by Stonck08** 2024-10-15 19:16 UTC
